package org.everapp.generated;

import java.lang.IllegalStateException;
import java.lang.String;

/**
 * GENERATED by MainGenerator from src/main/resources/domain.dsl — do not edit.
 */
public final class Agent {
  private AgentState state = AgentState.OFF;

  public AgentState state() {
    return state;
  }

  public void activate() {
    require(state == AgentState.OFF, "activate");
    state = AgentState.IDLE;
  }

  public void assignTask() {
    require(state == AgentState.IDLE, "assignTask");
    state = AgentState.WORKING;
  }

  public void completeTask() {
    require(state == AgentState.WORKING, "completeTask");
    state = AgentState.IDLE;
  }

  private void require(boolean allowed, String action) {
    if (!allowed) {
      throw new IllegalStateException("Cannot " + action + " from state " + state);
    }
  }
}
