package org.everapp.generator;

import org.antlr.v4.runtime.CharStream;
import org.antlr.v4.runtime.CharStreams;
import org.antlr.v4.runtime.CommonTokenStream;
import com.squareup.javapoet.ClassName;
import com.squareup.javapoet.FieldSpec;
import com.squareup.javapoet.JavaFile;
import com.squareup.javapoet.MethodSpec;
import com.squareup.javapoet.TypeSpec;
import javax.lang.model.element.Modifier;
import java.io.File;

// Ensure you run `mvn antlr4:antlr4` first to generate the parser classes
import org.everapp.MyDSLLexer;
import org.everapp.MyDSLParser;
import org.everapp.MyDSLParser.DomainContext;
import org.everapp.MyDSLParser.TransitionContext;

/**
 * Derives Java from a Kernel-DSL model: a state enum AND a stateful domain class
 * whose guarded transition methods come straight from the DSL's transition table.
 * An ~8-line model expands into two ready-to-compile source files.
 */
public class MainGenerator {

    private static final String PACKAGE = "org.everapp.generated";
    private static final String GENERATED_NOTE =
        "GENERATED by MainGenerator from src/main/resources/domain.dsl — do not edit.";

    public static void main(String[] args) throws Exception {
        // 1. Parse the DSL into an AST.
        CharStream input = CharStreams.fromFileName("src/main/resources/domain.dsl");
        MyDSLLexer lexer = new MyDSLLexer(input);
        MyDSLParser parser = new MyDSLParser(new CommonTokenStream(lexer));
        DomainContext domain = parser.domain();

        String domainName = domain.ID().getText();          // "Agent"
        String enumName = domainName + "State";              // "AgentState"
        ClassName stateType = ClassName.get(PACKAGE, enumName);
        String initialState = domain.states().ID(0).getText(); // first declared state

        File outputDir = new File("target/generated-sources/dsl");
        outputDir.mkdirs();

        // 2. Derive the state enum.
        TypeSpec.Builder enumBuilder = TypeSpec.enumBuilder(enumName)
            .addJavadoc(GENERATED_NOTE)
            .addModifiers(Modifier.PUBLIC);
        domain.states().ID().forEach(id -> enumBuilder.addEnumConstant(id.getText()));
        writeFile(enumBuilder.build(), outputDir);

        // 3. Derive the stateful domain class: one guarded method per transition.
        TypeSpec.Builder agentBuilder = TypeSpec.classBuilder(domainName)
            .addJavadoc(GENERATED_NOTE)
            .addModifiers(Modifier.PUBLIC, Modifier.FINAL)
            .addField(FieldSpec.builder(stateType, "state", Modifier.PRIVATE)
                .initializer("$T.$L", stateType, initialState)
                .build())
            .addMethod(MethodSpec.methodBuilder("state")
                .addModifiers(Modifier.PUBLIC)
                .returns(stateType)
                .addStatement("return state")
                .build());

        for (TransitionContext t : domain.transitions().transition()) {
            String action = t.actionName().getText();
            String from = t.fromState().getText();
            String to = t.toState().getText();
            agentBuilder.addMethod(MethodSpec.methodBuilder(action)
                .addModifiers(Modifier.PUBLIC)
                .addStatement("require(state == $T.$L, $S)", stateType, from, action)
                .addStatement("state = $T.$L", stateType, to)
                .build());
        }

        // The one hand-shaped invariant the generator guarantees: no illegal transition.
        agentBuilder.addMethod(MethodSpec.methodBuilder("require")
            .addModifiers(Modifier.PRIVATE)
            .addParameter(boolean.class, "allowed")
            .addParameter(String.class, "action")
            .beginControlFlow("if (!allowed)")
            .addStatement("throw new $T($S + action + $S + state)",
                IllegalStateException.class, "Cannot ", " from state ")
            .endControlFlow()
            .build());

        writeFile(agentBuilder.build(), outputDir);

        System.out.println("✅ Generated " + enumName + ".java and " + domainName
            + ".java in " + outputDir.getAbsolutePath());
    }

    private static void writeFile(TypeSpec type, File outputDir) throws Exception {
        JavaFile.builder(PACKAGE, type).build().writeTo(outputDir);
    }
}
